# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{maildir-queue}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Aaron Suggs"]
  s.date = %q{2010-01-15}
  s.description = %q{A simple queue API with a maildir backend. Also includes an HTTP API}
  s.email = %q{aaron@ktheory.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "examples/config.ru",
     "lib/maildir/queue.rb",
     "lib/maildir/web_queue.rb",
     "test/helper.rb",
     "test/test_maildir_queue.rb",
     "test/test_maildir_web_queue.rb"
  ]
  s.homepage = %q{http://github.com/ktheory/maildir-queue}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A simple queue API with a maildir backend.}
  s.test_files = [
    "test/helper.rb",
     "test/test_maildir_queue.rb",
     "test/test_maildir_web_queue.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rack-test>, [">= 0"])
      s.add_development_dependency(%q<ktheory-fakefs>, [">= 0"])
      s.add_runtime_dependency(%q<maildir>, [">= 0.3.0"])
      s.add_runtime_dependency(%q<sinatra>, [">= 0.0.0"])
      s.add_runtime_dependency(%q<json>, [">= 0.0.0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rack-test>, [">= 0"])
      s.add_dependency(%q<ktheory-fakefs>, [">= 0"])
      s.add_dependency(%q<maildir>, [">= 0.3.0"])
      s.add_dependency(%q<sinatra>, [">= 0.0.0"])
      s.add_dependency(%q<json>, [">= 0.0.0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rack-test>, [">= 0"])
    s.add_dependency(%q<ktheory-fakefs>, [">= 0"])
    s.add_dependency(%q<maildir>, [">= 0.3.0"])
    s.add_dependency(%q<sinatra>, [">= 0.0.0"])
    s.add_dependency(%q<json>, [">= 0.0.0"])
  end
end

